version: "3.9"

services:
  postgres:
    image: postgres:14.3-alpine
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      - POSTGRES_DB=antigaspi
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   depends_on: 
  #     - postgres
  #   restart: always
  #   ports:
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@soat.fr
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   links:
  #     - postgres
  api:
    build: .
    depends_on: 
      - postgres
    ports: 
      - "${APIPORT}:${APIPORT}"
      - "9229:9229"
    environment:
      - PGHOST=postgres
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
      - API_PORT=${APIPORT}
    links:
      - postgres