name: Build Deploy Azure
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Checkout tools repo
    - uses: actions/checkout@v3 
    
    - name: Download build artifact 
      uses: actions/download-artifact@v3 
      with:
        name: build-artifact
        path: build
    
    - name: Deploy to Azure WebApp  
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2 
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
        package: './build'